name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy script on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 172.200.213.41
          username: azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd SDA-Projects
            git pull origin main
            ./deploy.sh

